/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiskAnalysisRouteImport } from './routes/risk-analysis'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as CohortsRouteImport } from './routes/cohorts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const RiskAnalysisRoute = RiskAnalysisRouteImport.update({
  id: '/risk-analysis',
  path: '/risk-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortsRoute = CohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cohorts': typeof CohortsRoute
  '/pipeline': typeof PipelineRoute
  '/risk-analysis': typeof RiskAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cohorts': typeof CohortsRoute
  '/pipeline': typeof PipelineRoute
  '/risk-analysis': typeof RiskAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cohorts': typeof CohortsRoute
  '/pipeline': typeof PipelineRoute
  '/risk-analysis': typeof RiskAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/cohorts' | '/pipeline' | '/risk-analysis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/cohorts' | '/pipeline' | '/risk-analysis'
  id: '__root__' | '/' | '/admin' | '/cohorts' | '/pipeline' | '/risk-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CohortsRoute: typeof CohortsRoute
  PipelineRoute: typeof PipelineRoute
  RiskAnalysisRoute: typeof RiskAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/risk-analysis': {
      id: '/risk-analysis'
      path: '/risk-analysis'
      fullPath: '/risk-analysis'
      preLoaderRoute: typeof RiskAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohorts': {
      id: '/cohorts'
      path: '/cohorts'
      fullPath: '/cohorts'
      preLoaderRoute: typeof CohortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CohortsRoute: CohortsRoute,
  PipelineRoute: PipelineRoute,
  RiskAnalysisRoute: RiskAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
